# Generated by Django 5.0.1 on 2024-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_paneluser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='is_approved',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
