# Generated by Django 5.0.1 on 2024-03-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_paneluser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='item_process',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessments',
            name='item_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessments',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='created_by',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
