# Generated by Django 5.0.1 on 2024-03-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_assessments_is_approved_alter_assessments_created_by_and_more'),
        ('home', '0003_assessments_item_process_assessments_item_size_and_more'),
    ]

    operations = [
    ]
