# Generated by Django 5.0.1 on 2024-03-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20240308_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessments',
            name='item_process',
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='item_size',
        ),
        migrations.RemoveField(
            model_name='assessments',
            name='item_type',
        ),
    ]
