# Generated by Django 5.0.3 on 2024-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_assessments_item_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('banner', models.FileField(upload_to='')),
            ],
        ),
    ]
