# Generated by Django 5.0.3 on 2024-04-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
