# Generated by Django 5.0.3 on 2024-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_assessments_assessed_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessments',
            name='echo_team_remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assessments',
            name='user_remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assessments',
            name='assessed_mode',
            field=models.CharField(blank=True, choices=[('initial', 'Initial Phase'), ('processing', 'Processing Phase'), ('final', 'Final Phase')], default='initial', max_length=1000, null=True),
        ),
    ]
