# Generated by Django 5.0.1 on 2024-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_users_email_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_closing_time',
            field=models.TextField(default='2000-01-01T18:18', null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_opening_time',
            field=models.TextField(default='2000-01-01T18:18', null=True),
        ),
    ]
