# Generated by Django 5.0.1 on 2024-03-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_products_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_approved',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
