# Generated by Django 5.0.1 on 2024-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
