# Generated by Django 5.0.1 on 2024-01-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_refers'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
