# Generated by Django 5.0.1 on 2024-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_products_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='domains',
            name='is_approved',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
    ]
