# Generated by Django 5.0.1 on 2024-01-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='party2_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='party2_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
