# Generated by Django 5.0.1 on 2024-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_bids_party2_id_alter_bids_party2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='party2_id',
            field=models.CharField(default='x', max_length=100),
        ),
        migrations.AlterField(
            model_name='bids',
            name='party2_name',
            field=models.CharField(default='x', max_length=100),
        ),
    ]
