# Generated by Django 5.0.1 on 2024-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_bids_reffered_by_id_bids_reffered_by_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_approved',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
    ]
