# Generated by Django 5.0.1 on 2024-01-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_bids_party2_id_alter_bids_party2_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='manufacturer_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='refers',
            name='manufacturer_username',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='refers',
            name='referral_price',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refers',
            name='seller_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='refers',
            name='seller_username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
