# Generated by Django 5.0.1 on 2024-03-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_delete_referral_usertype_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
