# Generated by Django 5.0.1 on 2024-01-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_refers_manufacturer_id_refers_manufacturer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='manufacturer_id',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AlterField(
            model_name='refers',
            name='seller_id',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
