# Generated by Django 5.0.1 on 2024-03-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_bids_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='refers',
            name='reffered_req_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bids',
            name='img',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
