# Generated by Django 5.0.1 on 2024-03-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_refers_reffered_req_id_alter_bids_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refers',
            old_name='reffered_by_name',
            new_name='reffered_by_username',
        ),
    ]
