# Generated by Django 5.0.1 on 2024-01-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_refers_manufacturer_id_alter_refers_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refers',
            name='manufacturer_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='refers',
            name='seller_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
