# Generated by Django 5.0.3 on 2024-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_rename_reffered_by_name_refers_reffered_by_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscategory',
            name='is_approved',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='itemssubcategories',
            name='is_approved',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
    ]
