# Generated by Django 5.0.1 on 2024-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_refers_manufacturer_id_alter_refers_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='other_parties',
            field=models.TextField(null=True),
        ),
    ]
