# Generated by Django 5.0.3 on 2024-06-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_itemscategory_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='start_bid_price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
