# Generated by Django 5.0.1 on 2024-01-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_bids_other_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsSubCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category', models.CharField(max_length=200, null=True)),
                ('category_id', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_opening_time',
            field=models.TextField(null=True),
        ),
    ]
