# Generated by Django 5.0.3 on 2024-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_bids_start_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='start_bid_price',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
