# Generated by Django 5.0.1 on 2024-02-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_itemscategory_itemssubcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_closing_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='other_parties',
            field=models.TextField(default='[]'),
        ),
    ]
