# Generated by Django 5.0.1 on 2024-02-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_bids_bid_closing_time_alter_bids_other_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_win_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='is_approved',
            field=models.CharField(default='no', max_length=5),
        ),
    ]
