# Generated by Django 5.0.3 on 2024-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_bids_start_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscategory',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemssubcategories',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
