# Generated by Django 5.0.3 on 2024-07-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_itemscategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='user_domains',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='itemscategory',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemssubcategories',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
