# Generated by Django 5.0.1 on 2024-02-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_bids_bid_category_bids_bid_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
