# Generated by Django 5.0.1 on 2024-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_bids_bid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
