# Generated by Django 5.0.3 on 2024-07-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_unit_users_user_domains_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
