# Generated by Django 5.0.3 on 2024-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_delete_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
