# Generated by Django 5.0.1 on 2024-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_scraps_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_types',
            field=models.JSONField(default=list),
        ),
    ]
