# Generated by Django 5.0.1 on 2024-02-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_users_user_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
