# Generated by Django 5.0.1 on 2024-02-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='title',
        ),
    ]
